spring.application.name=premier-league-v2

# -----------------------------
# H2 Database Configuration
# -----------------------------
spring.datasource.url=jdbc:h2:mem:premier_league_v2_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=denner
spring.datasource.password=plapiv2@123
spring.jpa.hibernate.ddl-auto=update
server.port=9090

# -----------------------------
# JPA / Hibernate
# -----------------------------
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -----------------------------
# H2 Console
# -----------------------------
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# -----------------------------
# Swagger Path
# -----------------------------
springdoc.swagger-ui.path=/swagger-ui.html
